context:
  name: zae-limiter
  version: "0.6.1"
  python_min: "3.11"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/z/${{ name }}/zae_limiter-${{ version }}.tar.gz
  sha256: 9117433a4404d57321bc4fa45307bd39d20b2437483b5600ec41ae8a601d5983

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - aioboto3 >=12.0.0
    - boto3 >=1.34.0
    - click >=8.0.0
    - python-ulid >=3.0.0
    - types-aiobotocore >=2.0.0
    - types-aiobotocore-dynamodb >=2.0.0

tests:
  - python:
      imports:
        - zae_limiter
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/zeroae/zae-limiter
  summary: Rate limiting library backed by DynamoDB with token bucket algorithm
  license: MIT
  license_file: LICENSE
  documentation: https://zeroae.github.io/zae-limiter/
  repository: https://github.com/zeroae/zae-limiter

extra:
  recipe-maintainers:
    - sodre
