context:
  name: zae-limiter
  version: "0.10.0"
  python_min: "3.11"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/z/${{ name }}/zae_limiter-${{ version }}.tar.gz
  sha256: eb1a34858d7c400aea2a318dcc990e260bf6f0819f6c0c7aa4fa50f20dc4dd28

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
    - hatch-build-scripts >=1
    - ruff >=0.9.0
  run:
    - python >=${{ python_min }}
    - aioboto3 >=12.0.0
    - aws_lambda_builders >=1.40.0
    - boto3 >=1.34.0
    - click >=8.0.0
    - docker-py >=7.0.0
    - pip
    - python-ulid >=3.0.0
    - pyyaml >=6.0
    - questionary >=2.0

tests:
  - python:
      imports:
        - zae_limiter
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - zae-limiter --help
      - zae-limiter lambda-export --output lambda.zip
      - python -c "from zae_limiter import __version__; assert __version__ == '${{ version }}', f'Expected ${{ version }}, got {__version__}'"
    requirements:
      run:
        - pip

about:
  homepage: https://github.com/zeroae/zae-limiter
  summary: Rate limiting library backed by DynamoDB with token bucket algorithm
  license: MIT
  license_file: LICENSE
  documentation: https://zeroae.github.io/zae-limiter/
  repository: https://github.com/zeroae/zae-limiter

extra:
  recipe-maintainers:
    - sodre
